baseurl: ''

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - "*.ipynb"
  - "*.ipynb.raw.html"
  - vendor
  - template.ipynb.md

links:
  contributors: https://github.com/usnistgov/chimad-phase-field/graphs/contributors
  license: https://github.com/usnistgov/chimad-phase-field/blob/nist-pages/LICENSE
  repo: usnistgov/chimad-phase-field
  github: https://github.com/usnistgov/chimad-phase-field
  chat: https://gitter.im/usnistgov/chimad-phase-field
  members: https://docs.google.com/spreadsheets/d/112cDOOwzxLGbRx7yPte6HaXQgzQSXULrrVJLEmJvrKM/pubhtml?gid=764068827&single=true
  simmeta: https://github.com/usnistgov/chimad-phase-field/blob/master/_data/simulations

title: Phase Field Community Hub

plugins: [jekyll-coffeescript]

admin_email: 'chimad-phase-field-admin@list.nist.gov'
