baseurl: '/pfhub'

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - "*.ipynb"
  - "*.ipynb.raw.html"
  - vendor
  - template.ipynb.md

links:
  live_url: https://pages.nist.gov/pfhub
  raw_name: pfhub
  contributors: https://github.com/usnistgov/pfhub/graphs/contributors
  license: https://github.com/usnistgov/pfhub/blob/nist-pages/LICENSE.md
  repo: usnistgov/pfhub
  github: https://github.com/usnistgov/pfhub
  chat_room: usnistgov/chimad-phase-field
  chat: https://gitter.im/usnistgov/chimad-phase-field
  staticman_api: https://api.staticman.net/v2/entry/usnistgov/pfhub/master/simulations
  simmeta: https://github.com/usnistgov/pfhub/blob/master/_data/simulations
  maillist: chimad-phase-field@list.nist.gov
  maillist_subscribe: chimad-phase-field+subscribe@list.nist.gov
  maillist_unsubscribe: chimad-phase-field+unsubscribe@list.nist.gov
  maillist_archive: https://groups.google.com/a/list.nist.gov/forum/#!forum/chimad-phase-field


title: "PFHub"
subtitle: "Phase Field Community Hub"

plugins: [jekyll-coffeescript]

admin_email: 'chimad-phase-field-admin@list.nist.gov'

new_edit: 'http://prose.io/#wd15/pfhub/tree/master'
prose_edit: 'http://prose.io/#wd15/pfhub/edit/master'
github_edit: 'https://github.com/usnistgov/pfhub/edit/master'
source_edit: 'https://github.com/usnistgov/pfhub/blob/master'
history_edit: 'https://github.com/usnistgov/pfhub/commits/master'

prose:
  rooturl: 'wiki'
  siteurl: 'https://pages.nist.gov/pfhub'
  media: 'images'
  metadata:
    wiki:
      - name: "layout"
        field:
          element: "hidden"
          value: "wiki"
      - name: "title"
        field:
          value: "My Title"
          element: "text"
          label: "Page Title"
          placeholder: "My Title"
